In [56]:
pip install datatable

Collecting datatable
  Downloading datatable-1.0.0-cp39-cp39-win_amd64.whl (4.0 MB)
     ---------------------------------------- 4.0/4.0 MB 5.7 MB/s eta 0:00:00
Installing collected packages: datatable
Successfully installed datatable-1.0.0
Note: you may need to restart the kernel to use updated packages.

In [48]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time
import pandas as pd

In [49]:
driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))
url = "https://sistemaswebb3-listados.b3.com.br/indexPage/stocks"
driver.get(url)

In [50]:
time.sleep(5)
itens_por_paginas = driver.find_element(By.XPATH, '/html/body/app-root/app-stocks-index/div/form/div[4]/div[1]/div/div[1]/select').click()
botao_120 = driver.find_element(By.XPATH, '/html/body/app-root/app-stocks-index/div/form/div[4]/div[1]/div/div[1]/select/option[4]').click()

In [51]:
numero_paginas = driver.find_element(By.XPATH, '/html/body/app-root/app-stocks-index/div/form/div[4]/div[2]/div/pagination-controls/pagination-template/ul/li[7]/a/span[2]')
numero_paginas = int(numero_paginas.text)
numero_paginas

5

In [52]:
lista_de_tabela_por_pagina = []
for pagina in range(0, numero_paginas):
    time.sleep(5)
    tabela = driver.find_element(By.XPATH, '/html/body/app-root/app-stocks-index/div/form/div[3]/div/table')

    html_tabela = tabela.get_attribute("outerHTML")

    tabela_final = pd.read_html(html_tabela)[0]

    lista_de_tabela_por_pagina.append(tabela_final)
    
    botao_avancar_pagina = driver.find_element(By.XPATH, "/html/body/app-root/app-stocks-index/div/form/div[4]/div[2]/div/pagination-controls/pagination-template/ul/li[8]").click()
    
base_de_dados_completa = pd.concat(lista_de_tabela_por_pagina)

base_de_dados_completa

,Empresa,Código,Índices dos quais participa
0,3MDRN,MMMC34,BDRX
1,3R PETROLEUMON NM,RRRP3,"GPTW,IBOV,IBRA,IBXL,IBXX,IGCT,IGCX,IGNM,ITAG,I..."
2,3TENTOSON NM,TTEN3,"AGFS,IBRA,ICON,IGCT,IGCX,IGNM,ITAG,SMLL"
3,ABBVIEDRN,ABBV34,BDRX
4,ABC BRASILPN N2,ABCB4,"IBRA,IDIV,IFNC,IGCT,IGCX,ITAG,SMLL"
...,...,...,...
28,WILSON SONSON NM,PORT3,"IGCX,IGNM,ITAG"
29,WIZ COON NM,WIZC3,"GPTW,IBRA,IDIV,IFNC,IGCT,IGCX,IGNM,ITAG,SMLL"
30,YDUQS PARTON NM,YDUQ3,"IBOV,IBRA,IBXX,ICO2,ICON,IGCT,IGCX,IGNM,ITAG,SMLL"
31,ZAMP S.A.ON NM,ZAMP3,"IBRA,ICON,IGCT,IGCX,IGNM,ITAG,SMLL"
32,ZOOM VIDEODRN,Z1OM34,BDRX

In [55]:
indice_ibrx = base_de_dados_completa[base_de_dados_completa['Índices dos quais participa'].str.contains('IBOV', na = False)]
indice_ibrx

,Empresa,Código,Índices dos quais participa
1,3R PETROLEUMON NM,RRRP3,"GPTW,IBOV,IBRA,IBXL,IBXX,IGCT,IGCX,IGNM,ITAG,I..."
12,ALIANSCSONAEON NM,ALSO3,"IBOV,IBRA,IBXL,IBXX,IGCT,IGCX,IGNM,IMOB,ISEE,I..."
17,ALPARGATASPN N1,ALPA4,"IBOV,IBRA,IBXX,ICON,IGCT,IGCX,INDX,IVBX,SMLL"
24,AMBEV S/AON,ABEV3,"AGFS,GPTW,IBOV,IBRA,IBXL,IBXX,ICO2,ICON,INDX,I..."
34,AREZZO COON NM,ARZZ3,"AGFS,GPTW,IBOV,IBRA,IBXX,ICO2,ICON,IGCT,IGCX,I..."
...,...,...,...
11,VALEON NM,VALE3,"IBOV,IBRA,IBXL,IBXX,IDIV,IGCT,IGCX,IGNM,IMAT,I..."
15,VIAON NM,VIIA3,"GPTW,IBOV,IBRA,IBXL,IBXX,ICO2,ICON,IGCT,IGCX,I..."
16,VIBRAON NM,VBBR3,"IBOV,IBRA,IBXL,IBXX,ICO2,IDIV,IGCT,IGCX,IGNM,I..."
25,WEGON NM,WEGE3,"IBOV,IBRA,IBXL,IBXX,ICO2,IGCT,IGCX,IGNM,INDX,I..."
30,YDUQS PARTON NM,YDUQ3,"IBOV,IBRA,IBXX,ICO2,ICON,IGCT,IGCX,IGNM,ITAG,SMLL"